version: "1.0"
info:
  model: int-scaffold
packages:
- name: FLOW_TEST_NATIVEProject
  gitServerName: test1
  gitUrl: https://github.com/Pooja-Anand-IBM-2
  gitUsername: Pooja-Anand-IBM-2
  gitBranch: main
services:
- serviceName: project.flow_test_native.integrations:while_loop
  packages:
  - name: FLOW_TEST_NATIVEProject
    version: "1.0"
- serviceName: pub.compress:compressData
  packages:
  - name: WmPublic
    version: 11.1.0.0.2048
